### ISSUE TITLE
Why is this shorter ?

### ISSUE THREAD

**Issue by rdebath** [utleyja/get-brainfuck#1]
:smiley: 

Yours ...
``` bf
+++++++[>++++++++++++<-]>.++++++++++++++++++++.+.++++++++++.[-]<++++[>++
++++++<-]>.[-]<++++++++[>+++++++++++++<-]>+.++++++++++.[-]<++++[>+++++++
+<-]>.[-]<++++++++[>++++++++++++<-]>+.[-]<++++[>++++++++<-]>.[-]<+++++++
++[>+++++++++++++<-]>-.---------------.++++++++++++++.+.[-]<++++[>++++++
++<-]>.[-]<++++++++++.
```

Shorter ...
``` bf
>++++++++++++[<+++++++>-]<.>+++++[<++++>-]<.+.++++++++++.[-]>++++++++[<+
+++>-]<.>+++++++++[<++++++++>-]<+.++++++++++.[-]>++++++++[<++++>-]<.>+++
+++++[<++++++++>-]<+.[-]>++++++++[<++++>-]<.>++++++++++++[<+++++++>-]<.-
--------------.++++++++++++++.+.[-]>++++++++[<++++>-]<.[-]++++++++++.
```

Edit: What happened!?

**Comment by utleyja** [comment]
I apologize, but I am unfamiliar with the GitHub issue system. If you wish to contact me, please email me at jacob@utleyja.com.

**Comment by rdebath** [comment]
Um; you might be better off not looking but it's [over here](https://github.com/rdebath/Brainfuck/blob/master/extras/txtbf.c), with the `-Q` argument.

What I was trying to hint at though was the question of why doesn't your `sqrt` give optimal multiplications.

**Comment by utleyja** [comment]
I will look into this; it's been a while since I did any serious development on this program, but I will examine the optimization of the multiplication selection.

Thank you for taking the time to look over my and others' programs.

**Comment by utleyja** [comment]
The program has been improved so that it is now comprehensive of better code options; the program now seems to produce less code than the output of yours when given the same input!

**Comment by utleyja** [comment]
The program has been improved so that it is now comprehensive of better code options; the program seems to output less code than the output of yours when given the same input!

**Comment by rdebath** [comment]
Excellent! 
I think you answered the question too ie: `int(math.ceil(math.sqrt`. I didn't realise it was that simple.

Your next task, should you choose to accept it, ...
``` bf
+++++++[->++++++++++++<]>.[----<+++++>]<-.+.++++++++++.+[---->+<]>+++.++
+[-<+++>]<.++++++++++.+[---->+<]>+++.[-<+++>]<+.-[--->+<]>.---[-<++++>]<
.---------------.++++++++++++++.+.[---->+<]>+++.--[---<+>]<.
```
😈
